### PR TITLE
ADD CPF validation

### PR DESCRIPTION
**Pull request by karlprieb**
CPF validation with/without dot and dash separators

### CODE REVIEW

**Comment by gpedro** [comment]
thanks for contribution, but is missing verification algorithm.
look this: http://www.macoratti.net/alg_cpf.htm

**Comment by karlprieb** [comment]
Its true. verification algorithm is missing.
Thanks for the guide :)

I will update this PR.

**Comment by karlprieb** [comment]
This algorithm that you send me with this link is not working.
I find a working algorithm and applied to my function.

**Comment by gpedro** [comment]
LGTM! Ready for merge.

**Comment by dleitee** [comment]
Thank you!!

**Pull request merged**
